# Generated by Django 5.0.6 on 2024-07-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surtidor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
